DileepWick/vortext-online-io-games-platform

frontend/src/pages/Home.jsx
=> Change name

backend/controllers/orderController.js, backend/models/order.js, backend/models/user.js, backend/routes/order_Routes.js, backend/routes/userAuthenticationRoutes.js, frontend/dashboards/Orders_Components/ApprovedOrders.jsx, frontend/dashboards/Orders_Components/CompleteButton.jsx, frontend/dashboards/Orders_Components/Courier_Completed_Orders.jsx, frontend/dashboards/Orders_Components/View_Address_Button.jsx, frontend/dashboards/Orders_Components/View_Reason_Button.jsx, frontend/dashboards/Orders_Components/canceledOrderTable.jsx, frontend/dashboards/Orders_Components/completedOrdersTable.jsx, frontend/dashboards/Orders_Components/courier_current_orders.jsx, frontend/dashboards/Orders_Components/currentOrdersTable.jsx, frontend/dashboards/courier_dashboard.jsx, frontend/dashboards/order_manager_dashboard.jsx, frontend/src/App.jsx, frontend/src/components/header.jsx
New Features
1.View Address Button
2.View Cancellation reason button.
3.Courier dashboard
4.Courier status change button
5.Complted Orders ( order manager and courier )
=> Updated courier dashboard and order manager dashboard

frontend/dashboards/Customer suport.jsx, frontend/src/components/header.jsx
=> Customer Agent dashboard

backend/controllers/contact_us_controller.js, frontend/src/components/header.jsx, frontend/src/pages/Contact.jsx
Now data is passing through the form
=> Updated and fixed contact us

backend/controllers/contact_us_controller.js, frontend/dashboards/Customer suport.jsx, frontend/src/pages/Contact.jsx, frontend/src/pages/Support.jsx, frontend/src/style/contact.css
Added limits for contact us form
Redesign the support page
=> Contact us

frontend/dashboards/Customer suport.jsx, frontend/package-lock.json, frontend/package.json, frontend/src/App.jsx, frontend/src/main.jsx, frontend/src/pages/Cart_Page.jsx, frontend/src/pages/Home.jsx, frontend/src/pages/Support.jsx
=> Add helmet

frontend/dashboards/rentedGamesDash.jsx, frontend/dashboards/session_manager_dashbord.jsx, frontend/src/pages/HandleRentals.jsx
=> font error fixed

frontend/dashboards/Customer suport.jsx
Updated the issue where the toast is not showing up
=> Toast  not appearing

backend/controllers/article_controller.js, backend/routes/article_routes.js, frontend/dashboards/communityDashboard.jsx, frontend/src/pages/articles.jsx
user's profile picture should now appear immediately
=> article.jsx

frontend/src/pages/chat.jsx
=> chat lassana kara

frontend/src/pages/chat.jsx
=> final chat

frontend/src/pages/chat.jsx
=> chat error fix

backend/controllers/contact_us_controller.js, backend/controllers/notification_controller.js, backend/models/contact_us_model.js, backend/models/notification_model.js, backend/routes/contact_us_route.js, frontend/dashboards/Customer suport.jsx, frontend/src/App.jsx, frontend/src/components/header.jsx, frontend/src/pages/UserMessage.jsx
=> User and agent can chat

frontend/package-lock.json, frontend/package.json, frontend/src/App.jsx, frontend/src/components/Games/PuzzlePlatformGame.jsx, frontend/src/style/App.css
npm install lucide-react
in frontend
=> Game ekak damma malle

frontend/dashboards/Customer suport.jsx, frontend/src/App.jsx, frontend/src/components/ChatModal.jsx, frontend/src/pages/SupportChat.jsx, frontend/src/pages/UserMessage.jsx
userta reply krnna ba api kiyana de ahn paduwe inna kiyapan
=> Chat krnn plwn yako

frontend/dashboards/communityDashboard.jsx, frontend/src/pages/chat.jsx
=> dashboard, chat search

backend/controllers/messageController.js, backend/models/message.js, backend/routes/messageRoutes.js, frontend/src/pages/articles.jsx, frontend/src/pages/chat.jsx
=> make beautiful

frontend/src/components/header.jsx, frontend/src/pages/chat.jsx
Reverts Dileep-s-Works/Game-Store-MERN-ITP#145
=> Revert "header"

frontend/src/pages/Home.jsx, frontend/src/pages/RentalTableHistory.jsx, frontend/src/pages/TransactionHistoryPage.jsx
Reverts Dileep-s-Works/Game-Store-MERN-ITP#148
=> Revert "New new new"

frontend/dashboards/Payment_Management/Games_Sort.jsx, frontend/dashboards/Payment_Management/chart.jsx, frontend/dashboards/Payment_manager_dashboard.jsx, frontend/src/components/Games/WordSearch.jsx
=> gamefinished

frontend/src/pages/login.jsx
Eliminated frontend validation functions and validation checks from the signup process in login.jsx. The form now submits without local validation, relying on backend validation for user input.
=> Remove client-side validation from signup form

backend/controllers/article_controller.js, frontend/src/pages/articles.jsx
Enhanced error handling and user feedback in the articles page, including more robust response parsing, detailed error messages, and improved empty state UI. Also refactored backend controller for better readability and consistent formatting.
=> Improve article error handling and UI feedback

frontend/.gitignore, frontend/src/pages/Support.jsx, frontend/src/utils/getAPI.js
Introduced getAPI.js to centralize API base URL configuration based on environment. Updated Support.jsx to use the new API_BASE_URL constant. Also added .env to .gitignore to prevent committing environment variables.
=> Add API base URL utility and update Support page

frontend/package-lock.json, frontend/package.json, frontend/src/components/Games/ColorGuessingGame.jsx, frontend/src/pages/articles.jsx
Project scaffolding and initial file setup.
=> Initial commit

backend/package-lock.json, backend/package.json, frontend/package-lock.json, frontend/package.json, frontend/src/pages/articles.jsx, frontend/src/pages/chat.jsx
Reverts DileepWick/vortext-online-io-games-platform#174
=> Revert "Add socket.io to backend and frontend dependencies"

frontend/src/pages/articles.jsx
Refactored the articles page and CreatePostModal to enhance responsiveness and accessibility across devices. Adjusted padding, font sizes, button layouts, and image dimensions for better mobile and desktop experiences. Updated class names to use responsive Tailwind CSS utilities and improved UI consistency throughout the page.
=> Improve articles page and modal responsiveness

frontend/src/pages/GamingSessions.jsx, frontend/src/pages/HandleRentals.jsx
Changed background colors from black to white and updated text colors for better readability across GamingSessions and HandleRentals pages. Adjusted card and button styles to match the new light theme, and improved spacing and contrast for a more consistent user experience.
=> Update UI to use light theme and improve text contrast

.gitignore, backend/controllers/article_controller.js, backend/middleware/passport.js, backend/models/article_model.js, frontend/package-lock.json, frontend/package.json, frontend/src/App.jsx, frontend/src/components/AboutUs.jsx, frontend/src/components/Chatbot.jsx, frontend/src/components/footer.jsx, frontend/src/components/header.jsx, frontend/src/pages/Contact.jsx, frontend/src/pages/Page.jsx, frontend/src/pages/Support.jsx, frontend/src/pages/articles.jsx, frontend/src/pages/chat.jsx, frontend/src/pages/profile.jsx, package-lock.json, package.json
Introduced a function to handle and validate user input, improving the robustness of the input processing workflow.
=> Add new feature to process user input
